import type { Metadata }
    from "next";
import { Poppins, Inter, } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout";
import AOSWapper from "@/components/ui/aos";


const poppins = Poppins({
    subsets: ["latin"],
    weight: [
        "300",
        "400",
        "500",
        "600",
        "700"
    ],
    variable: "--font-poppins"
});
const inter = Inter({
    subsets: ["latin"],
    weight: [
        "400", "500", "600", "700"
    ],
    variable: "--font-inter"
});


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({ children }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={
                ` ${poppins.variable
                }  ,${inter.variable
                }`
            }><AOSWapper />
                <Layout>{children}</Layout>
            </body>
        </html >
    );
}
